services:
  php74:
    build:
      context: .
      args:
        PHP_VERSION: "7.4"
    volumes:
      - "../:/app"
    working_dir: /app
    environment:
      - GOOGLE_API_KEY
      - GOOGLE_CREDENTIALS_FILE

  php81:
    build:
      context: .
      args:
        PHP_VERSION: "8.1"
    volumes:
      - "../:/app"
    working_dir: /app
    environment:
      - GOOGLE_API_KEY
      - GOOGLE_CREDENTIALS_FILE
